### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by L1cardo** [renaudjenny/SwiftClockUI#7]
Is it possible to change color of arms and the indicators？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by renaudjenny** [comment]
Hi @L1cardo,
Unfortunately, there is not possibility at this point. But it could be a very nice and cool improvement to do!

I think to use `.environment` for that, something like

```swift
ClockView()
    .environment(\.clockDate, $date)
    .environment(\.clockStyle, .steampunk)
    .environment(\.clockArmsColor, .red)
```

I just noticed that you can change the color of the whole Clock by doing
```
ClockView()
    .environment(\.clockDate, $date)
    .environment(\.clockStyle, .steampunk)
    .foregroundColor(.red)
```
And you will have a result like this:
![image](https://user-images.githubusercontent.com/2297556/84598372-1fb1de80-ae62-11ea-8685-79d6be15f04e.png)
I don't think it's what you're looking for as you've mentioned "arms and indicators". So we should have a better granularity of elements colour.

Anyway, if you're confident enough to do it yourself, feel free to add some `EnvironmentKey` (you can get inspiration from what's inside the `Environment` folder. Otherwise, tell me and I'll be happy to do it myself.

Moreover, thank you very much for you interest about this library. You're my very first external issue in any of my repository! That's something!

**Comment by L1cardo** [comment]
I just thought that if we can modify the colors, we can create more beautiful clocks!
Like below 
![96FD98E3-D586-4C95-980A-A34026879F2B](https://user-images.githubusercontent.com/33802186/84598650-e0ee4980-ae9e-11ea-85da-84fbde5dadb0.jpeg)
![CA8A7762-5532-4793-9A95-7923F9E785F5](https://user-images.githubusercontent.com/33802186/84598662-ed72a200-ae9e-11ea-914a-9c3337c49a3f.jpeg)

**Comment by renaudjenny** [comment]
Totally agree.
Do you think it's better to have a colour per arm? Like one colour for minute, a potential different for hour, etc?

**Comment by L1cardo** [comment]
It would  be great to have different color for per arm.
Different color for hour indicators and minute indicators will be extremely cool!

**Comment by renaudjenny** [comment]
I will work on it!

**Comment by L1cardo** [comment]
> I will work on it!

Thanks mate!

**Comment by renaudjenny** [comment]
Done.

Basically you can use something like this now:
```
ClockView()
    .environment(\.clockDate, $date)
    .environment(\.clockArmColors, ArmColors(
        minute: .red,
        hour: .blue
    ))
    .environment(\.clockBorderColor, .orange)
    .environment(\.clockIndicatorsColor, .green)
```
It's on master right now. I will do some test in a real app with Dark mode and so, update the README, and I a release tag. But tomorrow :D

UI Snapshot test has been added as well.

**Comment by renaudjenny** [comment]
* [X] README updated
* [X] Tested on iPhone (Light and Dark mode)
* [X] Tagged

:)

**Comment by L1cardo** [comment]
God! I love you mate!!
Thanks very much!!!
